### PR TITLE
feat: mostly mvp level complete

### PR DESCRIPTION
**Pull request by nickelskevin**
New, simplified data model. Persistence working and the UI component flow first pass completed.

**- What I did**
* Refactored to a new, simplified data model. 
* Persistence working and the UI component flow first pass completed.

**- How I did it**

**- How to verify it**
* run the app
* add a device
* check the devices screen to see the device
* add a receiver after selecting a device

**- Description for the changelog**

feat: Refactored to a new, simplified data model. Persistence is now working and the UI component flow first pass completed.

### CODE REVIEW

**Comment by cconstab** [comment]
Devices adding works and looks great and the add receivers panel works including the drop down for the device (nice)..

I cannot add receivers though, I get nothing in the list once added just a rude null is not a subtype of String  message after I have added a receiver..

Screen Shot 2022-09-26 at 7 26 44 PM

**Comment by nickelskevin** [comment]
Did you try adding a receiver?

**Comment by nickelskevin** [comment]
checking in fix to the above. should be working now.

**Comment by cconstab** [comment]
Few issues:-

 Deleting receivers or devices does not seem to work.
 The back button (top left) goes back through screens not back to the main screen like I would have expected

**Comment by cconstab** [comment]
> checking in fix to the above. should be working now.

Yup fixed ..

**Comment by cconstab** [comment]
I can delete now but it feels like it does not work every time..... 

Receivers & devices I have to delete twice to remove them from list

**Review by cconstab — APPROVED** [review]
Looks good next to make sure it works end to end.. Will test that when I get to LV

**Pull request merged**
